<a href="https://colab.research.google.com/github/TiesHRL/Farmtrace/blob/main/SeminarAPG.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
if True:
  print("Welcome to the Chat GPT code to generate ")

Ties is gemeen en jaloers


In [3]:
import numpy as np

def score_based_greedy_search(time_series):
    n = len(time_series)
    # Initialize the DAG with no edges
    dag = np.zeros((n, n))
    # Initialize the scores array
    scores = np.zeros(n)
    # Calculate the scores for each node
    for i in range(n):
        for j in range(i+1, n):
            delta = time_series[j] - time_series[i]
            scores[i] += delta * (delta > 0)
    # Perform the greedy search
    for i in range(n):
        for j in range(i+1, n):
            if scores[j] > scores[i]:
                dag[i][j] = 1
    return dag

# Example usage:
time_series = [1, 2, 1, 3, 4, 5, 6, 7, 8, 9]
dag = score_based_greedy_search(time_series)
print(dag)


[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
